packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  esbuild: true
  sharp: true
  '@next/swc-darwin-arm64': true
  '@turbo/darwin-arm64': true
minimumReleaseAgeExclude:
  - '@turbo/darwin-64@2.11.3'
  - '@turbo/darwin-arm64@2.11.3'
  - '@turbo/linux-64@2.11.3'
  - '@turbo/linux-arm64@2.11.3'
  - '@turbo/windows-64@2.11.3'
  - '@turbo/windows-arm64@2.11.3'
  - turbo@2.11.3
