/**
 * Provider-aware Connected Apps content.
 * Keys resolve through apps.* message catalogs — never invent capabilities Sena does not implement.
 */

export type ProviderContent = {
  provider: string;
  logoSrc: string;
  /** Official brand name (not translated). */
  brandName: string;
  categoryKey: string;
  shortDescriptionKey: string;
  overviewKey: string;
  benefitKeys: string[];
  prerequisiteKeys: string[];
  connectionStepKeys: string[];
  goodToKnowKey: string;
  howCreateKey: string;
  howUpdateKey: string;
  howCancelKey?: string;
  connectCtaKey: string;
  comingSoonOverviewKey?: string;
};

const CATALOG: Record<string, ProviderContent> = {
  paystack: {
    provider: 'paystack',
    logoSrc: '/assets/providers/paystack.svg',
    brandName: 'Paystack',
    categoryKey: 'paymentsCategory',
    shortDescriptionKey: 'paystackDescription',
    overviewKey: 'paystackOverview',
    benefitKeys: ['paystackBenefit1', 'paystackBenefit2', 'paystackBenefit3'],
    prerequisiteKeys: ['paystackPrereq1', 'paystackPrereq2'],
    connectionStepKeys: ['paystackStep1', 'paystackStep2', 'paystackStep3'],
    goodToKnowKey: 'paystackGoodToKnow',
    howCreateKey: 'paystackHowCreate',
    howUpdateKey: 'paystackHowUpdate',
    connectCtaKey: 'connectPaystack',
  },
  flutterwave: {
    provider: 'flutterwave',
    logoSrc: '/assets/providers/flutterwave.svg',
    brandName: 'Flutterwave',
    categoryKey: 'paymentsCategory',
    shortDescriptionKey: 'flutterwaveDescription',
    overviewKey: 'flutterwaveOverview',
    benefitKeys: ['flutterwaveBenefit1', 'flutterwaveBenefit2', 'flutterwaveBenefit3'],
    prerequisiteKeys: ['flutterwavePrereq1', 'flutterwavePrereq2'],
    connectionStepKeys: ['flutterwaveStep1', 'flutterwaveStep2', 'flutterwaveStep3'],
    goodToKnowKey: 'flutterwaveGoodToKnow',
    howCreateKey: 'flutterwaveHowCreate',
    howUpdateKey: 'flutterwaveHowUpdate',
    connectCtaKey: 'connectFlutterwave',
  },
  stripe: {
    provider: 'stripe',
    logoSrc: '/assets/providers/stripe.svg',
    brandName: 'Stripe',
    categoryKey: 'paymentsCategory',
    shortDescriptionKey: 'stripeDescription',
    overviewKey: 'stripeOverview',
    benefitKeys: ['stripeBenefit1', 'stripeBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'stripeOverview',
  },
  zoho_invoice: {
    provider: 'zoho_invoice',
    logoSrc: '/assets/providers/zoho.svg',
    brandName: 'Zoho Invoice',
    categoryKey: 'accountingCategory',
    shortDescriptionKey: 'zohoInvoiceDescription',
    overviewKey: 'zohoInvoiceOverview',
    benefitKeys: ['zohoInvoiceBenefit1', 'zohoInvoiceBenefit2', 'zohoInvoiceBenefit3'],
    prerequisiteKeys: ['zohoInvoicePrereq1', 'zohoInvoicePrereq2', 'zohoInvoicePrereq3'],
    connectionStepKeys: [
      'zohoInvoiceStep1',
      'zohoInvoiceStep2',
      'zohoInvoiceStep3',
      'zohoInvoiceStep4',
      'zohoInvoiceStep5',
    ],
    goodToKnowKey: 'zohoInvoiceGoodToKnow',
    howCreateKey: 'zohoInvoiceHowCreate',
    howUpdateKey: 'zohoInvoiceHowUpdate',
    connectCtaKey: 'connectZohoInvoice',
  },
  zoho_books: {
    provider: 'zoho_books',
    logoSrc: '/assets/providers/zoho.svg',
    brandName: 'Zoho Books',
    categoryKey: 'accountingCategory',
    shortDescriptionKey: 'zohoBooksDescription',
    overviewKey: 'zohoBooksOverview',
    benefitKeys: ['zohoBooksBenefit1', 'zohoBooksBenefit2', 'zohoBooksBenefit3'],
    prerequisiteKeys: ['zohoBooksPrereq1', 'zohoBooksPrereq2', 'zohoBooksPrereq3'],
    connectionStepKeys: [
      'zohoBooksStep1',
      'zohoBooksStep2',
      'zohoBooksStep3',
      'zohoBooksStep4',
      'zohoBooksStep5',
    ],
    goodToKnowKey: 'zohoBooksGoodToKnow',
    howCreateKey: 'zohoBooksHowCreate',
    howUpdateKey: 'zohoBooksHowUpdate',
    connectCtaKey: 'connectZohoBooks',
  },
  quickbooks: {
    provider: 'quickbooks',
    logoSrc: '/assets/providers/quickbooks.svg',
    brandName: 'QuickBooks Online',
    categoryKey: 'accountingCategory',
    shortDescriptionKey: 'quickbooksDescription',
    overviewKey: 'quickbooksOverview',
    benefitKeys: ['quickbooksBenefit1', 'quickbooksBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'quickbooksOverview',
  },
  xero: {
    provider: 'xero',
    logoSrc: '/assets/providers/xero.svg',
    brandName: 'Xero',
    categoryKey: 'accountingCategory',
    shortDescriptionKey: 'xeroDescription',
    overviewKey: 'xeroOverview',
    benefitKeys: ['xeroBenefit1', 'xeroBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'xeroOverview',
  },
  google_calendar: {
    provider: 'google_calendar',
    logoSrc: '/assets/providers/google-calendar.svg',
    brandName: 'Google Calendar',
    categoryKey: 'calendarCategory',
    shortDescriptionKey: 'googleCalendarDescription',
    overviewKey: 'googleCalendarOverview',
    benefitKeys: [
      'googleCalendarBenefit1',
      'googleCalendarBenefit2',
      'googleCalendarBenefit3',
      'googleCalendarBenefit4',
    ],
    prerequisiteKeys: ['googleCalendarPrereq1', 'googleCalendarPrereq2', 'googleCalendarPrereq3'],
    connectionStepKeys: [
      'googleCalendarStep1',
      'googleCalendarStep2',
      'googleCalendarStep3',
      'googleCalendarStep4',
      'googleCalendarStep5',
      'googleCalendarStep6',
    ],
    goodToKnowKey: 'googleCalendarGoodToKnow',
    howCreateKey: 'googleCalendarHowCreate',
    howUpdateKey: 'googleCalendarHowUpdate',
    howCancelKey: 'googleCalendarHowCancel',
    connectCtaKey: 'connectGoogleCalendar',
  },
  outlook_calendar: {
    provider: 'outlook_calendar',
    logoSrc: '/assets/providers/outlook.svg',
    brandName: 'Outlook Calendar',
    categoryKey: 'calendarCategory',
    shortDescriptionKey: 'outlookCalendarDescription',
    overviewKey: 'outlookCalendarOverview',
    benefitKeys: ['outlookCalendarBenefit1', 'outlookCalendarBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'outlookCalendarOverview',
  },
  whatsapp: {
    provider: 'whatsapp',
    logoSrc: '/assets/providers/whatsapp.svg',
    brandName: 'WhatsApp Business',
    categoryKey: 'communicationsCategory',
    shortDescriptionKey: 'whatsappDescription',
    overviewKey: 'whatsappOverview',
    benefitKeys: ['whatsappBenefit1', 'whatsappBenefit2', 'whatsappBenefit3'],
    prerequisiteKeys: ['whatsappPrereq1', 'whatsappPrereq2'],
    connectionStepKeys: ['whatsappStep1', 'whatsappStep2', 'whatsappStep3'],
    goodToKnowKey: 'whatsappGoodToKnow',
    howCreateKey: 'whatsappHowCreate',
    howUpdateKey: 'whatsappHowUpdate',
    connectCtaKey: 'connectWhatsApp',
  },
  gmail: {
    provider: 'gmail',
    logoSrc: '/assets/providers/gmail.svg',
    brandName: 'Gmail',
    categoryKey: 'communicationsCategory',
    shortDescriptionKey: 'gmailDescription',
    overviewKey: 'gmailOverview',
    benefitKeys: ['gmailBenefit1', 'gmailBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'gmailOverview',
  },
  outlook_mail: {
    provider: 'outlook_mail',
    logoSrc: '/assets/providers/outlook.svg',
    brandName: 'Outlook Mail',
    categoryKey: 'communicationsCategory',
    shortDescriptionKey: 'outlookMailDescription',
    overviewKey: 'outlookMailOverview',
    benefitKeys: ['outlookMailBenefit1', 'outlookMailBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'outlookMailOverview',
  },
  brevo: {
    provider: 'brevo',
    logoSrc: '/assets/providers/brevo.svg',
    brandName: 'Brevo',
    categoryKey: 'communicationsCategory',
    shortDescriptionKey: 'brevoDescription',
    overviewKey: 'brevoOverview',
    benefitKeys: ['brevoBenefit1', 'brevoBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'brevoOverview',
  },
  channex: {
    provider: 'channex',
    logoSrc: '/assets/providers/channex.svg',
    brandName: 'Channex',
    categoryKey: 'bookingChannelsCategory',
    shortDescriptionKey: 'channexDescription',
    overviewKey: 'channexOverview',
    benefitKeys: ['channexBenefit1', 'channexBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'channexOverview',
  },
  booking_com: {
    provider: 'booking_com',
    logoSrc: '/assets/providers/booking-com.svg',
    brandName: 'Booking.com',
    categoryKey: 'bookingChannelsCategory',
    shortDescriptionKey: 'bookingComDescription',
    overviewKey: 'bookingComOverview',
    benefitKeys: ['bookingComBenefit1', 'bookingComBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'bookingComOverview',
  },
  airbnb: {
    provider: 'airbnb',
    logoSrc: '/assets/providers/airbnb.svg',
    brandName: 'Airbnb',
    categoryKey: 'bookingChannelsCategory',
    shortDescriptionKey: 'airbnbDescription',
    overviewKey: 'airbnbOverview',
    benefitKeys: ['airbnbBenefit1', 'airbnbBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'airbnbOverview',
  },
  expedia: {
    provider: 'expedia',
    logoSrc: '/assets/providers/expedia.svg',
    brandName: 'Expedia',
    categoryKey: 'bookingChannelsCategory',
    shortDescriptionKey: 'expediaDescription',
    overviewKey: 'expediaOverview',
    benefitKeys: ['expediaBenefit1', 'expediaBenefit2'],
    prerequisiteKeys: ['comingSoonPrereq'],
    connectionStepKeys: [],
    goodToKnowKey: 'comingSoonGoodToKnow',
    howCreateKey: 'comingSoonHow',
    howUpdateKey: 'comingSoonHow',
    connectCtaKey: 'connect',
    comingSoonOverviewKey: 'expediaOverview',
  },
};

export function getProviderContent(provider: string): ProviderContent | null {
  return CATALOG[provider] || null;
}

export function listProviderContent(): ProviderContent[] {
  return Object.values(CATALOG);
}

export function providerLogoSrcFromContent(provider: string): string | null {
  return CATALOG[provider]?.logoSrc || null;
}
