export * from './components/brand';
export * from './components/layout';
export * from './components/elements';
export * from './templates/account';
export * from './templates/reservation';
export * from './templates/payment';
export * from './templates/stay';
export * from './templates/staff';
export * from './templates/operations';
export * from './templates/subscription';
export * from './templates/security';
export * from './templates/support';
export * from './templates/editorial';
export * from './registry';
export * from './sender';
export declare function sendBookingConfirmationEmail(params: {
    guestEmail: string;
    guestName: string;
    reference: string;
    propertyName: string;
    roomType: string;
    checkInDate: string;
    checkOutDate: string;
    nights: number;
    totalAmountFormatted: string;
    propertyAddress?: string;
    propertyPhone?: string;
}): Promise<import("./sender").SendEmailResult>;
export declare function sendBankTransferInstructionsEmail(params: {
    guestEmail: string;
    guestName: string;
    reference: string;
    propertyName: string;
    bankName: string;
    accountNumber: string;
    accountName: string;
    amountFormatted: string;
    whatsappContact?: string;
    propertyPhone?: string;
}): Promise<import("./sender").SendEmailResult>;
export declare function sendPaymentReceiptEmail(params: {
    guestEmail: string;
    guestName: string;
    reference: string;
    paymentReference: string;
    propertyName: string;
    amountFormatted: string;
    paymentMethod: string;
    paidAt: string;
}): Promise<import("./sender").SendEmailResult>;
//# sourceMappingURL=index.d.ts.map