import assert from 'node:assert/strict';
import { writeFileSync } from 'node:fs';
import { requireIsolatedTestDatabase } from './require-isolated-test-database';
import bcrypt from 'bcryptjs';
requireIsolatedTestDatabase();

async function run() {
  const { db, organizations, properties, users, propertyMembers, organizationMembers, roomTypes, rooms, reservations, payments, housekeepingTasks, eq, and } = await import('../packages/database/src/index');
  const { ReservationService } = await import('../packages/reservations/src/index');
  const { PaymentService } = await import('../packages/payments/src/index');
  const { createHold, releaseHold, checkAvailability } = await import('../packages/inventory/src/index');
  const { HousekeepingService } = await import('../packages/housekeeping/src/index');
  const runId = crypto.randomUUID().slice(0, 8);
  let passed = 0;
  function pass(name: string) { passed++; console.log(`PASS ${name}`); }
  const [org] = await db.insert(organizations).values({ name: 'Local QA', slug: `local-${runId}` }).returning();
  const [property] = await db.insert(properties).values({ organizationId: org.id, name: 'Sena Local QA A', slug: `local-a-${runId}`, code: `QA-${runId}`, address: 'Local only', phone: '', email: 'qa@example.invalid', timezone: 'Africa/Lagos', currency: 'NGN' }).returning();
  const [other] = await db.insert(properties).values({ organizationId: org.id, name: 'Sena Local QA B', slug: `local-b-${runId}`, code: `QB-${runId}`, address: 'Local only', phone: '', email: 'qb@example.invalid' }).returning();
  const [rt] = await db.insert(roomTypes).values({ propertyId: property.id, name: 'QA Double', bedType: 'Double', basePriceMinorUnits: 10000, capacity: 2, totalInventory: 1 }).returning();
  const [room] = await db.insert(rooms).values({ propertyId: property.id, roomTypeId: rt.id, roomNumber: '101', housekeepingStatus: 'clean', operationalStatus: 'available' }).returning();
  const [otherType] = await db.insert(roomTypes).values({ propertyId: other.id, name: 'Other QA Double', bedType: 'Double', basePriceMinorUnits: 10000, capacity: 2, totalInventory: 1 }).returning();
  const [otherRoom] = await db.insert(rooms).values({ propertyId: other.id, roomTypeId: otherType.id, roomNumber: '201', housekeepingStatus: 'clean', operationalStatus: 'available' }).returning();
  const input = { propertyId: property.id, roomTypeId: rt.id, checkInDate: '2027-01-01', checkOutDate: '2027-01-03', numGuests: 1, adults: 1, children: 0, source: 'walk_in' as const, paymentStatus: 'pay_later' as const, paidAmountMinorUnits: 0, guest: { fullName: 'Local QA Guest', email: `guest-${runId}@example.invalid`, phone: '', preferences: [] } };
  const allocations = await Promise.allSettled(Array.from({ length: 8 }, () => ReservationService.create(input)));
  assert.equal(allocations.filter(r => r.status === 'fulfilled').length, 1);
  pass('eight concurrent allocations of the last room produce exactly one reservation');
  const stay = (allocations.find(r => r.status === 'fulfilled') as PromiseFulfilledResult<any>).value;
  await assert.rejects(ReservationService.checkIn(stay.id, otherRoom.id));
  pass('cross-property room assignment is rejected');
  await db.update(rooms).set({ housekeepingStatus: 'dirty' }).where(eq(rooms.id, room.id));
  await assert.rejects(ReservationService.checkIn(stay.id, room.id));
  await db.update(rooms).set({ housekeepingStatus: 'clean' }).where(eq(rooms.id, room.id));
  pass('dirty room cannot be checked in');
  const checkins = await Promise.all([ReservationService.checkIn(stay.id, room.id), ReservationService.checkIn(stay.id, room.id)]);
  assert.equal((await db.query.rooms.findFirst({ where: eq(rooms.id, room.id) }))?.operationalStatus, 'occupied');
  pass('repeated check-in is idempotent');
  const pay = { reservationId: stay.id, amountMinorUnits: 10000, provider: 'manual' as const, method: 'cash' as const };
  const receipts = await Promise.all(Array.from({ length: 8 }, () => PaymentService.recordPayment(pay, `qa-payment-${runId}`)));
  assert.equal(new Set(receipts.map(r => r.id)).size, 1);
  assert.equal((await db.query.reservations.findFirst({ where: eq(reservations.id, stay.id) }))?.paidAmountMinorUnits, 10000);
  pass('eight payment retries produce one receipt and one balance increment');
  await Promise.all([PaymentService.recordPayment({ ...pay, amountMinorUnits: 5000 }, `qa-pay-b-${runId}`), PaymentService.recordPayment({ ...pay, amountMinorUnits: 5000 }, `qa-pay-c-${runId}`)]);
  assert.equal((await db.query.reservations.findFirst({ where: eq(reservations.id, stay.id) }))?.paidAmountMinorUnits, 20000);
  pass('concurrent distinct payments preserve both balance increments');
  await Promise.all([ReservationService.checkOut(stay.id), ReservationService.checkOut(stay.id)]);
  assert.equal((await db.query.housekeepingTasks.findMany({ where: eq(housekeepingTasks.roomId, room.id) })).length, 1);
  assert.equal((await db.query.rooms.findFirst({ where: eq(rooms.id, room.id) }))?.housekeepingStatus, 'dirty');
  await HousekeepingService.updateStatus(property.id, room.id, 'clean');
  assert.equal((await db.query.rooms.findFirst({ where: eq(rooms.id, room.id) }))?.housekeepingStatus, 'clean');
  pass('repeated checkout creates one cleaning task; cleaning restores room readiness');
  const hold = await createHold(property.id, rt.id, '2027-02-01', '2027-02-03');
  await assert.rejects(ReservationService.create({ ...input, checkInDate: '2027-02-01', checkOutDate: '2027-02-03' }));
  const heldBooking = await ReservationService.create({ ...input, checkInDate: '2027-02-01', checkOutDate: '2027-02-03', holdId: hold.holdId } as any, undefined, `qa-held-${runId}`);
  const retried = await ReservationService.create({ ...input, checkInDate: '2027-02-01', checkOutDate: '2027-02-03', holdId: hold.holdId } as any, undefined, `qa-held-${runId}`);
  assert.equal(heldBooking.id, retried.id);
  pass('active hold protects the final room; conversion and retry allocate once');
  await Promise.all([ReservationService.cancel(heldBooking.id), ReservationService.cancel(heldBooking.id)]);
  assert.equal((await checkAvailability(property.id, rt.id, '2027-02-01', '2027-02-03')).minAvailable, 1);
  pass('repeated cancellation restores inventory exactly once');
  const password = `Local-QA-${runId}!`;
  const [owner] = await db.insert(users).values({ fullName: 'Local QA Owner', email: `owner-${runId}@example.invalid`, passwordHash: await bcrypt.hash(password, 10), isActive: true, emailVerified: new Date() }).returning();
  await db.insert(propertyMembers).values({ userId: owner.id, propertyId: property.id, role: 'owner' });
  await db.insert(organizationMembers).values({ userId: owner.id, organizationId: org.id, role: 'owner' });
  writeFileSync('/tmp/sena-craft-fixture.json', JSON.stringify({ propertyId: property.id, otherPropertyId: other.id, roomId: room.id, roomTypeId: rt.id, otherRoomId: otherRoom.id, ownerId: owner.id, email: owner.email, password, reservationId: stay.id, slug: property.slug }));
  console.log(`${passed} operational integrity checks passed; local UI fixture saved.`);
  process.exit(0);
}
run().catch(error => { console.error(error); process.exit(1); });
